### ISSUE TITLE
Scrolling stops before the targetScrollTop is reached

### ISSUE THREAD

**Issue by ClaudioKirchmair** [Nolanus/ng2-page-scroll#53]
I had a problem on a mobile device with an ie browser. The scroll did only perform one easing step instead all steps and stopped afterwards. This problem can be prevented by a simple condition: Has newScrollTop the same value as targetScrollTop. Changes are in **bold**.

src\ng2-page-scroll-service.ts
157:  if (stopNow **&& (newScrollTop === _pageScrollInstance.targetScrollTop)**) {
158:    _this.stopInternal(false, _pageScrollInstance);
159:  }

Please fix this soon, so that I can continue to use your plugin.

**Comment by Nolanus** [comment]
Hi @ClaudioKirchmair,

could you please give some more details on the cause for the misbehavior in mobile IE you describe? As you already provide a change suggestion you possibly debugged the script, you might now the reason for the `stopNow` variable to be true although the scroll target was not reached. However, note that debugging this part is difficult, as it is working with the current time and waiting at a breakpoint does not cause the javascript clock to stop.

**Comment by ClaudioKirchmair** [comment]
My config params:
PageScrollConfig.defaultScrollOffset = 50;
PageScrollConfig.defaultDuration = 500;

My scrolling call:
let pageScrollInstance: PageScrollInstance = PageScrollInstance.simpleInstance(this.document, previousScreenIdString);
this.pageScrollService.start(pageScrollInstance);

During the debugging I found out that it was a kind of race condition. When I put an alert in the "pageScrollInstance.timer" function then it would work, because of "_pageScrollInstance.endTime <= currentTime". I only run debug sessions with alerts because I couldn't debug on the smartphone (windows phone with an old IE browser). I think that "!_pageScrollInstance.setScrollTopPosition(newScrollTop)" didn't work and so the scrolling stopped after one intervall instead going to the end. 

My quick fix solved this problem because he only stops when the targetScrollTop is reached. It's kind of a safety check that everything went right. I would provide better info if the error is easier to track down.

**Comment by Nolanus** [comment]
Hi @ClaudioKirchmair, can you please try the latest version 3.2.3. I hope the issue with your IE browser is fixed in there due to changes for #55.

**Comment by ClaudioKirchmair** [comment]
It doesn't fix the problem. It scrolls a very short distance and then it stops.

**Comment by Nolanus** [comment]
Closing due to the inability to properly reproduce the issue. Please comment when more details are available on how to reproduce and on which setting (device, windows phone version, ie version, etc.)
